### ISSUE TITLE
Causes random freezes

### ISSUE THREAD

**Issue by AndreaOrru** [seagle0128/all-the-icons-ivy-rich#10]
Sometimes, and only when I have `all-the-icons-ivy-rich` enabled, opening `ivy` freezes Emacs for ~10 seconds. I couldn't identify why, but I'm open to suggestions. :)

I use the very last git revision of Emacs 27, if that helps.
```
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, cairo version 1.17.3) of 2020-05-15
```

**Comment by seagle0128** [comment]
Does `C-g` work in this case? It's better get some backtraces for troubleshooting. Another suggestion is profiling: https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html

**Comment by AndreaOrru** [comment]
Nope, Emacs becomes entirely unresponsive. :(
I'll try profiling.

**Comment by seagle0128** [comment]
Any update?

**Comment by aspiers** [comment]
I'm guessing it happens when the icon fonts are loaded.  For some reason font loading has managed to temporarily freeze up every single Linux system I've used in the last 20 years.

**Comment by AndreaOrru** [comment]
`(setq inhibit-compacting-font-caches t)` seems to somewhat help.

**Comment by seagle0128** [comment]
`(setq inhibit-compacting-font-caches t)` should be helpful.
It's not an issue of `all-the-icons-ivy-rich`, right? I will close it and feel free to reopen if you find the issue of this package.

**Comment by aspiers** [comment]
IMHO it would be worth documenting this.

**Comment by seagle0128** [comment]
I believe it has been documented in [all-the-icons](https://github.com/domtronn/all-the-icons.el/blob/5b661c3b8722f79d1286d1c9cb0bd0e889c34082/README.md#slow-rendering).

**Comment by aspiers** [comment]
Ah cool, thanks.
