### ISSUE TITLE
not used if other packages load at a later stage

### ISSUE THREAD

**Issue by dsvensson** [seagle0128/all-the-icons-ivy-rich#15]
I noticed that when I load `all-the-icons-ivy-rich` before `counsel-projectile`, `counsel-projectile-find-file` for example will not get decorated until I toggle `all-the-icons-ivy-rich` off/on. Is there any way around this or is the intended use to load everything up front?

Other than that, a big thanks! Another chunk of elisp gone from my config.

**Comment by seagle0128** [comment]
You need to load and enable `counsel-projectile` before enabling `all-the-icons-ivy-rich-mode`.
For better performance, please also enable it before `ivy-rich-mode` .

**Comment by seagle0128** [comment]
Update README in a87cd16。
