### ISSUE TITLE
All-the-icons-ivy-rich-mode breaks counsel-find-file behavior

### ISSUE THREAD

**Issue by dalanicolai** [seagle0128/all-the-icons-ivy-rich#20]
After updating this package today, activating `all-the-icons-ivy-rich-mode` breaks the counsel-find-file behavior. It does no longer find my `git` directory in my home directory. Also, when in `counsel-find-file` I press `~` to start from home directory, and subsequently type some letter to narrow down, then scrolling up down stopped working. Maybe you have an idea which commit caused this? Otherwise, let me know, and I can maybe help track it down...

**Comment by seagle0128** [comment]
Can you share more details? Try to update `all-the-icons` to the latest. Some commits broke and the issue has been addressed by https://github.com/domtronn/all-the-icons.el/commit/d9ad756066c8a82d49e56d5248c74caa53827b8f. Not sure if you encounter the same issue.

**Comment by dalanicolai** [comment]
After updating `all-the-icons` the errors are gone. I saw that you had made several commits when I responded to the PR, so I assumed that might have caused the errors. But indeed `all-the-icons` was updated simultaneously with this package (I am using Spacemacs). Anyway, with this newest update everything works fine again, thanks!

**Comment by seagle0128** [comment]
Good to know.
