### ISSUE TITLE
all-the-icons-ivy-rich--project-root is slow, please add option to disable it

### ISSUE THREAD

**Issue by honmaple** [seagle0128/all-the-icons-ivy-rich#21]
```
(benchmark 1000 '(all-the-icons-ivy-rich--full-path nil))
(fset 'all-the-icons-ivy-rich--project-root 'ignore)
(benchmark 1000 '(all-the-icons-ivy-rich--full-path nil))
```

```
Elapsed time: 9.525189s (1.519488s in 28 GCs)
Elapsed time: 0.026319s
```

**Comment by seagle0128** [comment]
A new commit 9135ec9d9774210f94c447b4bcb7620870a8558a to add `all-the-icons-ivy-rich--project-root` back. It's only activated for project/projectile commands and skips parsing the remote files for better performance.

**Comment by seagle0128** [comment]
Also add new option `all-the-icons-ivy-rich-project` in c3807938018631edebda9703d45ffa702490d98b.
