### ISSUE TITLE
Couldn't show these icons in projectile-find-file

### ISSUE THREAD

**Issue by quarkquartet** [seagle0128/all-the-icons-ivy-rich#24]
I'm using doom emacs. I love this icons and installed it for ivy icons in Doom. It works well except that when I use `projectile-find-file` the icons disappear.

For example, this is the normal case:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/26316540/150897714-0bbdad45-6492-4c6e-8c4f-d72bdfd7608b.png">

This is the result when running `projectile-find-file`:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/26316540/150898109-f2f0b469-2628-4af0-a0b2-4975429d7429.png">

My config is
```emacs-lisp
(defun icons-displayable-p ()
  "Return non-nil if `all-the-icons' is displayable."
  (and (display-graphic-p)
       (require 'all-the-icons nil t)))

(when (icons-displayable-p)
(use-package! all-the-icons-ivy-rich
  ;:ensure t
  :hook (ivy-mode . all-the-icons-ivy-rich-mode)
  (all-the-icons-ivy-rich-reload))
  )

;; More friendly display transformer for Ivy
(use-package! ivy-rich
  :hook ((counsel-projectile-mode . ivy-rich-mode) ; MUST after `counsel-projectile'
         (ivy-rich-mode . (lambda ()
                            "Use abbreviate in `ivy-rich-mode'."
                            (setq ivy-virtual-abbreviate
                                  (or (and ivy-rich-mode 'abbreviate) 'name)))))
  :init
  ;; For better performance
  ;(ivy-rich-mode 1)
  (setq ivy-rich-parse-remote-buffer nil))
```

Is this the problem with my setting, or all-the-icons-ivy-rich, or Doom?

**Comment by seagle0128** [comment]
You should use [counsel-projectile](https://github.com/ericdanan/counsel-projectile). Use `counsel-projectile-find-file` instead.

**Comment by quarkquartet** [comment]
> You should use [counsel-projectile](https://github.com/ericdanan/counsel-projectile). Use `counsel-projectile-find-file` instead.

Tried this. Same result.

**Comment by quarkquartet** [comment]
> You should use [counsel-projectile](https://github.com/ericdanan/counsel-projectile). Use `counsel-projectile-find-file` instead.

Tried to reload the `all-the-icons-ivy-rich-mode` manually after I first run `counsel-projectile`. Then it works.

I think it is still some problem about how to enable the rich mode **after** the `counsel-projectile`. The current best plan for me is
```emacs-lisp
(use-package! all-the-icons-ivy-rich
  :ensure t
  :init (all-the-icons-ivy-rich-mode 1))

(use-package! ivy-rich
  :ensure t
  :init (ivy-rich-mode 1))
(after! counsel-projectile
  (all-the-icons-ivy-rich-reload))
```
Not sure whether this is the best idea.

**Comment by seagle0128** [comment]
Enable `all-the-icons-ivy-rich-mode` after `ivy-rich`.
