### ISSUE TITLE
all-the-icons-ivy-rich uses different types of icons in ivy-rich

### ISSUE THREAD

**Issue by was0A** [seagle0128/all-the-icons-ivy-rich#25]
![alt](https://emacs-china.org/uploads/default/original/3X/a/0/a00bee665af1dd7767065eb2763b41e3dec0c09b.png)
![alt](https://emacs-china.org/uploads/default/original/3X/c/8/c8fc103be0367556d795c506d2908b5751b7d388.png)
 
As these pictures show, it seems like that the all-the-icons-ivy-rich uses different types of icons to show the icon before the file.
I just install the package all-the-icons-ivy-rich and enable it, then the errors happend like these pictures.
I have tried to fix this bug. I reinstalled the package but that didn't work.
(And I installed a package called cnfonts)

Who could tell me what happend and how to fix? Thanks!

**Comment by was0A** [comment]
It's a issue of `spacemacs-theme`, not `all-the-icons-ivy-rich`'s

**Comment by seagle0128** [comment]
Check `ivy-current-match` face or other faces of spacemacs-theme.
