### ISSUE TITLE
What are "u, v, c@, f@, c@u, U..." in describle-variable/function?

### ISSUE THREAD

**Issue by ianyepan** [seagle0128/all-the-icons-ivy-rich#26]
As titled, what do the values in the second column of "describe-variable" and "describe-function" represent?

### Screenshot

<img width="448" alt="image" src="https://user-images.githubusercontent.com/36686900/161699193-1d8757b9-c4d1-4dd1-bf39-d6e51dbd4b35.png">

**Comment by seagle0128** [comment]
Please see `all-the-icoons-ivy-rich-symbol-class`.

```
Function:
f function
c command
C interactive-only command
m macro
M special-form
g cl-generic
p pure
s side-effect-free
@ autoloaded
! advised
- obsolete

Variable:
u custom (U modified compared to global value)
v variable
l local (L modified compared to default value)
- obsolete

Other:
a face
t cl-type
```

**Comment by ianyepan** [comment]
Gotcha, thanks!
