### ISSUE TITLE
icon的高度不一样导致在minibuffer中上下快速移动时显示异常

### ISSUE THREAD

**Issue by georgealbert** [seagle0128/all-the-icons-ivy-rich#27]
由于icon的高度不一样，部分icon比其他的高，icon高的行和其他行的行距不一致，导致在minibuffer中上下快速移动时，显示有些闪屏，不好看。`  (setq all-the-icons-ivy-rich-icon t)`关掉或者`  (setq all-the-icons-ivy-rich-icon-size 0.65)` 设置小一些后，就没有这个问题

字体配置   `(set-face-attribute 'default nil :font "FantasqueSansMono Nerd Font 18")`
下图为 size=0.65后的截图：
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/5278617/170165310-65b60e2e-2c72-4c6b-90d3-85e7743b5fb5.png">

**Comment by seagle0128** [comment]
这个没法解决，是上游`all-the-icons`的问题，`all-the-icons-ivy-rich-icon-size` 就是用来作为调整的workaround。

**Comment by georgealbert** [comment]
好的，谢谢！
