### ISSUE TITLE
all-the-icons-ivy-rich breaks ivy-avy

### ISSUE THREAD

**Issue by tam17aki** [seagle0128/all-the-icons-ivy-rich#3]
After `(all-the-icons-ivy-rich-mode 1)`, and invoking `ivy-avy` in the ivy-minibuffer, the target alphabets (shown in front of each candidate) will be broken (it seems the alphabet character itself is replaced as a "image file").

- when `(all-the-icons-ivy-rich-mode 1)`:
![スクリーンショット 2020-02-19 19 38 05](https://user-images.githubusercontent.com/761295/74826698-63328b00-534f-11ea-93e1-740eeb7d1854.png)

- when `(all-the-icons-ivy-rich-mode -1)`:
![スクリーンショット 2020-02-19 19 36 45](https://user-images.githubusercontent.com/761295/74826596-34b4b000-534f-11ea-87a4-40a3f374dbb6.png)

I'm using `(define-key ivy-minibuffer-map (kbd "C-;") 'ivy-avy)`.

Best regards,
Akira

**Comment by seagle0128** [comment]
Please test.

**Comment by tam17aki** [comment]
I have tested. It works perfectly.

Thank you very much,
Akira

**Comment by seagle0128** [comment]
Welcome.
