### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (cl-no-applicable-method project-root nil)

### ISSUE THREAD

**Issue by swarnendubiswas** [seagle0128/all-the-icons-ivy-rich#30]
The last commit gives rise to the following error, when I try to invoke `projectile-switch-project` from outside of a project, say the `*scratch*` buffer. It seems that commit `e489b08aeae53c0288474495b5c0e6847ba1005d` is the culprit. The code works if I am already within a project.

`Error in post-command-hook (ivy--queue-exhibit): (cl-no-applicable-method project-root nil)`

**Comment by seagle0128** [comment]
It should be fixed.

Root Cause:
`project-root` is a macro while no a function.

Reference:
https://github.com/emacs-lsp/lsp-mode/issues/2335
https://github.com/emacs-ess/ESS/issues/1052
