### ISSUE TITLE
Formatting in some locations is thrown off after change to `all-the-icons-ivy-rich--format-icon`

### ISSUE THREAD

**Issue by davep** [seagle0128/all-the-icons-ivy-rich#33]
Since the most recent update I'm noticing that different icons now seem to be formatting as having slightly different width, or spacing. To illustrate, when running `counsel-find-file` the resulting view of a directory of files looks like this:

![Screenshot 2023-04-16 at 15 03 30](https://user-images.githubusercontent.com/28237/232329101-37954e27-5710-4b59-9f40-0545bdd5ca68.png)

Note that everything from `Makefile` down is pushing the rest of the line over a little.

I think I've narrowed the cause down to 5e798a4495993ef2c5bf66243140d6474363851a -- if revert that commit everything lines up again (along the way to narrowing down the cause I did notice that setting `all-the-icons-ivy-rich-icon-size` to no more than 0.95 also made things line up).

**Comment by seagle0128** [comment]
Can you please try this ?

```elisp
(defun all-the-icons-ivy-rich--format-icon (icon)
  "Format ICON'."
  (let* ((props (get-text-property 0 'face icon))
         (family (plist-get props :family))
         (face (if all-the-icons-ivy-rich-color-icon
                   (or (plist-get props :inherit) props)
                 'all-the-icons-ivy-rich-icon-face))
         (new-face `(:inherit ,face
                     :family ,family
                     :height ,all-the-icons-ivy-rich-icon-size)))
    (format "%s%s"
            (propertize " " 'display '((space :relative-width 0.1)))
            (propertize icon 'face new-face))))
```

**Comment by davep** [comment]
@seagle0128 Perfect! That does the trick!
