### ISSUE TITLE
Error with counsel-projectile-switch-project

### ISSUE THREAD

**Issue by tastytea** [seagle0128/all-the-icons-ivy-rich#4]
Version: 1.1.0 / 20200219.1713

When I run `counsel-projectile-switch-project`, I get the error: `Error in post-command-hook (ivy--queue-exhibit): (void-function nil)`

`counsel-projectile-switch-project` is part of [counsel-projectile](https://github.com/ericdanan/counsel-projectile). Tested with: 0.3.1 / 20200214.1450

**Comment by tastytea** [comment]
Minimal `init.el` (assuming counsel-projectile, ivy-rich and all-the-icons-ivy-rich are installed):

``` elisp
(package-initialize)

(require 'counsel-projectile)
(counsel-projectile-mode t)

(require 'ivy-rich)
(ivy-rich-mode 1)

(require 'all-the-icons-ivy-rich)
(all-the-icons-ivy-rich-mode 1)
```

**Comment by seagle0128** [comment]
Can you please provide the details below?

- Emacs version
- OS version
- Backtrace (`M-x toggle-debug-on-error`)

**Comment by tastytea** [comment]
Emacs versions: 27.0.50 (from 2019-12-23) and 26.3  
OS: Gentoo Linux  

I couldn't get a backtrace with `M-x toggle-debug-on-error`.

**Comment by seagle0128** [comment]
Wired. I couldn't reproduce it. So how do you confirm it's caused by `all-the-icons-ivy-rich`?

Updated: Reinstall `all-the-icons` and `all-the-icons-ivy-rich` to retry, please.

**Comment by tastytea** [comment]
It works now with the current versions of `all-the-icons` and `all-the-icons-ivy-rich`. Thank you! :tada:
