### ISSUE TITLE
Some Ivy candicates icons and string are interval with extra spaces

### ISSUE THREAD

**Issue by stardiviner** [seagle0128/all-the-icons-ivy-rich#7]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/378699/76694551-18d2ce80-66af-11ea-9f4b-f778af3620e2.png)

You can see the Ivy candidate like `amread-mode.el` has extra spaces between icon and text.

**Comment by seagle0128** [comment]
It's related to the fonts. Change the icon size via `all-the-icons-ivy-rich-icon-size` or try other fonts.

**Comment by stardiviner** [comment]
Thanks, I reduced size solved this problem.
(setq all-the-icons-ivy-rich-icon-size 0.9)
