### ISSUE TITLE
Misalignment due to fonts

### ISSUE THREAD

**Issue by glepnir** [seagle0128/all-the-icons-ivy-rich#8]
maybe this problem casued  by font . Is it possible to fix?  maybe can adjust icon height ?like doom fixed some error https://github.com/Brettm12345/emacs-doom-themes/commit/5f79b0c6afbfda4d03053c0f93ef7b4d7c9ffc3a
![image](https://user-images.githubusercontent.com/41671631/76923514-8af51e80-690e-11ea-9738-c1881ccc45cf.png)

**Comment by seagle0128** [comment]
Duplicate with #7.
