### ISSUE TITLE
Wrong color of match part with counsel-mode and regex.

### ISSUE THREAD

**Issue by Vonfry** [seagle0128/all-the-icons-ivy-rich#9]
## Description

The first picture is `counsel-M-x`  with searching by regex `^ivy`, which has wrong color of the match part.

![截屏2020-03-3117 25 21](https://user-images.githubusercontent.com/3413119/78010279-c2cf7d80-7374-11ea-8560-29145a6cabfc.png)
![截屏2020-03-3117 25 42](https://user-images.githubusercontent.com/3413119/78010287-c531d780-7374-11ea-98fe-359accfcf6e3.png)

## Reproduce
`emacs -Q` and then:
```
(add-to-list 'load-path "<path>/memoize")
(add-to-list 'load-path "<path>/ivy")
(add-to-list 'load-path "<path>/swiper")
(add-to-list 'load-path "<path>/counsel")
(add-to-list 'load-path "<path>/all-the-icons")
(add-to-list 'load-path "<path>/all-the-icons-ivy-rich")
(add-to-list 'load-path "<path>/ivy-rich")

(require 'memoize)
(require 'ivy)
(require 'swiper)
(require 'counsel)
(require 'all-the-icons)
(require 'all-the-icons-ivy-rich)
(require 'ivy-rich)

(ivy-mode t)
(counsel-mode t)
(ivy-rich-mode t)
(all-the-icons-ivy-rich-mode t)
```

## Misc

It is similiar to raxod502/prescient.el#48

**Comment by seagle0128** [comment]
Because the first character is the SPC (actually is `SPC+icon+SPC`), the regexp is not able to find the `i`.

**Comment by Vonfry** [comment]
~Could I think the problem is caused by ivy self? Thank for your answer.~

Sorry, I think it is not the actual reason.

**Comment by Vonfry** [comment]
I am not familiar with ivy code. 

In the first picture, it cannot show the color, but the result is matched. I also tried other regex getting the same outcome(correct items but wrong color).

According to your description, the result should not be matched correctly.

**Comment by seagle0128** [comment]
`all-the-icons-ivy-rich` adds extra info before the ivy strings. It's as designed.
